### ISSUE TITLE
in example, missing data is not coloured

### ISSUE THREAD

**Issue by njtierney** [njtierney/ggmissing#12]
Basically, running the code

```
library(dplyr)
library(ggplot2)
library(ggmissing)

brfss %>%
  mutate(miss_cat = miss_cat(., "PHYSHLTH", "MENTHLTH")) %>% 
  ggplot(data = .,
         aes(x = shadow_shift(PHYSHLTH),
             y = shadow_shift(POORHLTH),
             colour = miss_cat)) + 
  geom_point() 
```

Produces a plot with the legend: "Not Missing", when in fact there is missing data in POORHLTH:

```
sum(is.na(brfss$POORHLTH))
```

Unsure why that is happening.

**Comment by dicook** [comment]
Its ok, typo in you code. You have MENTHLTH in the miss_cat command instead of POORHLTH. Fixing this generates the colored points.

**Comment by njtierney** [comment]
No fixed and demonstrated in README with geom_missing_point()
